#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "beszel"
name = "Beszel"
description.en = "Lightweight server monitoring"
description.fr = "Monitoring de serveurs"

version = "0.19.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://www.beszel.dev/"
admindoc = "https://beszel.dev/guide/hub-installation#binary"
code = "https://github.com/henrygd/beszel"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = [ "amd64", "arm64", "armhf" ]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/henrygd/beszel/releases/download/v0.19.0/beszel_linux_amd64.tar.gz"
    amd64.sha256 = "63b20d6ca328dc08e588126da2e13f8bece6ae875de5f25a058f48cb6ea19998"
    arm64.url = "https://github.com/henrygd/beszel/releases/download/v0.19.0/beszel_linux_arm64.tar.gz"
    arm64.sha256 = "303f144f865a24b95b539740222dc65dc376b25526c8430eb5b093f3759e337c"
    armhf.url = "https://github.com/henrygd/beszel/releases/download/v0.19.0/beszel_linux_arm.tar.gz"
    armhf.sha256 = "ac021f786fc966149756b6a50628e68cadb18e2ca8ca016523f64866a7748c00"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "beszel_linux_amd64.tar.gz"
    autoupdate.asset.arm64 = "beszel_linux_arm64.tar.gz"
    autoupdate.asset.armhf = "beszel_linux_arm.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]
